added functionality for likes and friends.
Fytonzo/java-filmorate pull request #2
Opened 2022-12-07 08:55 UTC by Fytonzo

2022-12-08 08:47 UTC, NikolaiDem requested changes

2022-12-08 08:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmService filmService;
private final

2022-12-08 08:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @ResponseBody
Аннотация избыточна, потому что @RestController уже включает в себя @ResponseBody

2022-12-08 08:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    UserService userService;
private final

2022-12-08 08:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      private LocalDate releaseDate;
releaseDate тоже не должна быть null

2022-12-08 08:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      @JsonCreator
А с какой целью здесь используется JsonCreator?

2022-12-08 08:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public void setLikes(HashSet<Long> likes) {
Лучше использовать интерфейс вместо конкретного типа     
void setLikes(Set<Long> likes) {}

2022-12-08 08:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>      @JsonCreator
А с какой целью здесь используется JsonCreator?

2022-12-08 08:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public void setFriends(HashSet<Integer> friends) {
Лучше использовать интерфейс вместо конкретного типа
void setLikes(Set likes) {}

2022-12-08 08:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Set<Long> filmLikes = getFilm(filmId).getLikes();
Еще нужно проверить, что пользователь с userId существует. Например, вызвать userStorage.getUser(userId). Аналогично для метода удаления лайка.

2022-12-08 08:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Set<Long> filmLikes = getFilm(filmId).getLikes();
Чтобы не получать все лайки, можно в Film добавить методы addLike(...) и removeLike(...) и использовать их.

2022-12-08 08:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Set<Integer> user1Friends = inMemoryUserStorage.getUser(idUser1).getFriends();
inMemoryUserStorage.getUser(idUser1) и inMemoryUserStorage.getUser(idUser2) используются в коде дважды, лучше вынести юзеров в отдельные переменные.
Аналогично для остальных методов.

2022-12-08 08:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        inMemoryUserStorage.getUser(idUser1).setFriends((HashSet<Integer>) user1Friends);
Вместо обновления всего сета лучше сделать методы в User-е addFriend(...) и removeFriend(...)
Аналогично для removeFriend(...)

2022-12-08 08:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (film.getName().isBlank()) {
Так как на поля Film навешаны аннотации валидации (@NotBlank, @Positive и т.д.), то явные проверки здесь можно убрать, а в методы контроллера к аргументу Film добавить аннотацию @Valid, чтобы активировать проверку объектов spring-boot-ом. 
Например, Film addFilm(@Valid @RequestBody Film film)

2022-12-08 08:47 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        if (user.getEmail().isBlank() || (!user.getEmail().contains("@"))) {
Так как на поля User навешаны аннотации валидации (@notblank, @positive и т.д.), то явные проверки здесь можно убрать, а в методы контроллера к аргументу User добавить аннотацию @Valid, чтобы активировать проверку объектов spring-boot-ом.
Например, User addUser(@Valid @RequestBody User user)

2022-12-09 08:51 UTC, Fytonzo commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    FilmService filmService;
Исправлено

2022-12-09 08:51 UTC, Fytonzo commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    @ResponseBody
Исправлено

2022-12-09 08:52 UTC, Fytonzo commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    UserService userService;
Исправлено

2022-12-09 08:53 UTC, Fytonzo commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      private LocalDate releaseDate;
Добавлена аннотация @NotNull

2022-12-09 12:47 UTC, Fytonzo commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
> +    public void setLikes(HashSet<Long> likes) {
Исправлено

2022-12-09 12:48 UTC, Fytonzo commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    public void setFriends(HashSet<Integer> friends) {
Исправлено

2022-12-09 12:57 UTC, Fytonzo commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryFilmStorage.java
> +        if (film.getName().isBlank()) {
Исправлено

2022-12-09 12:57 UTC, Fytonzo commented on src/main/java/ru/yandex/practicum/filmorate/storage/InMemoryUserStorage.java
> +        if (user.getEmail().isBlank() || (!user.getEmail().contains("@"))) {
Исправлено

2022-12-09 13:20 UTC, Fytonzo commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Set<Long> filmLikes = getFilm(filmId).getLikes();
Исправлено

2022-12-09 13:20 UTC, Fytonzo commented on src/main/java/ru/yandex/practicum/filmorate/service/FilmService.java
> +        Set<Long> filmLikes = getFilm(filmId).getLikes();
Исправлено

2022-12-09 13:40 UTC, Fytonzo commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        inMemoryUserStorage.getUser(idUser1).setFriends((HashSet<Integer>) user1Friends);
Исправлено

2022-12-09 13:40 UTC, Fytonzo commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        Set<Integer> user1Friends = inMemoryUserStorage.getUser(idUser1).getFriends();
Исправлено

2022-12-09 15:39 UTC, Fytonzo commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
>      @JsonCreator
Избыточно, убрал

2022-12-09 15:39 UTC, Fytonzo commented on src/main/java/ru/yandex/practicum/filmorate/model/Film.java
>      @JsonCreator
Избыточно, убрал

2022-12-09 16:17 UTC, closed without merging