Add database
Fytonzo/java-filmorate pull request #4
Opened 2023-01-08 16:47 UTC by Fytonzo

added database and tests

2023-01-09 18:35 UTC, NikolaiDem requested changes

2023-01-09 18:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +import ru.yandex.practicum.filmorate.model.Genre;
Неиспользуемые импорты.

2023-01-09 18:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    private final FilmService filmService;
Лучше использовать отдельный сервис для жанров

2023-01-09 18:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/controller/MpaController.java
> +    private final FilmService filmService;
Лучше использовать отдельный сервис для Mpa

2023-01-09 18:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        return jdbcTemplate.query(sql, new FilmResultSetExtractor(jdbcTemplate, this));
Почему маппинг ResultSet в List<Film> вынесен в отдельный класс?

2023-01-09 18:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dataextractor/FilmResultSetExtractor.java
> +            film.setMpa(filmStorage.getMpaById(rs.getInt("rating_id")));
Здесь возникает проблема "N+1 query". Одним запросом получены все N фильмов, и для каждого фильма нужно сделать еще по 4 запроса (на получение mpa, жанров и лайков), то есть дополнительных N (*4) запросов. 
Лучше mpa получить в том же запросе, где получаются фильмы (добавить джойн к mpa).
А жанры можно получить одним запросом, но для всех фильмов сразу. Тогда останется только распределить их по фильмам. Аналогично для лайков.

2023-01-09 18:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        }else{
Code Style : пропущены пробелы
} else {
Аналогично исправить во всех классах.

2023-01-09 18:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +                    jdbcTemplate.update("INSERT INTO film_genre(film_id, genre_id) VALUES(?,?)",
Для множественного обновления лучше использовать jdbcTemplate.batchUpdate(String sql, final BatchPreparedStatementSetter pss), чтобы сделать это одним запросом.

2023-01-09 18:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        if (film.getReleaseDate().isBefore(FILMSTARTDATE)) {
Валидацию лучше перенести в сервис. Задача БД только прочитать и записать данные.

2023-01-09 18:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +            for(Long userId : film.getLikes()){
Лайки обновлять не нужно. Они меняются с использованием соответствующих эндпоинтов.

2023-01-09 18:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +                jdbcTemplate.update("INSERT INTO film_genre(film_id, genre_id) " +
Использовать batchUpdate(...)

2023-01-09 18:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        }else{
В каком случае вернется false, и нужна ли эта ветка?

2023-01-09 18:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        checkFilmInDb(filmId);
Существование юзера и фильма лучше проверить в сервисе, чтобы выявить возможную ошибку чуть ранее.

2023-01-09 18:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/FilmDbStorage.java
> +        checkFilmInDb(filmId);
Существование юзера и фильма лучше проверить в сервисе, чтобы выявить возможную ошибку чуть ранее.

2023-01-09 18:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dataextractor/UserResultSetExtractor.java
> +            SqlRowSet getUserFriends = jdbcTemplate.queryForRowSet("SELECT friend_id FROM friendship " +
Друзей можно получить в одном запросе с юзерами (с помощью джойна к friendship). Тогда дополнительные запросы не понадобятся.

2023-01-09 18:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dataextractor/UserResultSetExtractor.java
> +    private final UserStorage userStorage;
Не используется.

2023-01-09 18:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +        return jdbcTemplate.query(sql, new UserResultSetExtractor(jdbcTemplate, this));
Можно использовать анонимный класс или лямбду.

2023-01-09 18:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +        if ((user.getName()==null)||(user.getName().isBlank())) {
Валидацию лучше перенести в сервис.

2023-01-09 18:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +        }else{
Такая ветка избыточна.

2023-01-09 18:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +        if(checkUserInDb(userId)&&checkUserInDb(friendId)){
Проверки лучше сделать в сервисе.

2023-01-09 18:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +                        jdbcTemplate.queryForObject("SELECT id FROM status WHERE description='confirmed'",
Зачем таблица status?

2023-01-09 18:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +            SqlRowSet getFriends = jdbcTemplate.queryForRowSet("SELECT friend_id FROM friendship WHERE user_id=?",
Ссылки на объекты лучше обозначать существительными)

2023-01-09 18:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/dao/UserDbStorage.java
> +    private User makeUser(ResultSet rs) throws SQLException {
Метод дублируется с UserResultSetExtractor.extractData(...)

2023-01-09 18:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/model/User.java
> +    private int id = 0;
Лучше удалить, присвоение id сделать на стороне репозитория.

2023-01-09 18:35 UTC, NikolaiDem commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +        List<User> commonFriends = new ArrayList<>();
Поиск общих друзей лучше сделать в репозитории с помощью джойнов.

2023-01-09 18:35 UTC, NikolaiDem commented on src/main/resources/data.sql
> +INSERT INTO genre (id, genre_name) VALUES (1, 'Комедия');
Лучше использовать MERGE INTO, а DELETE FROM удалить.

2023-01-10 17:08 UTC, Fytonzo commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +import ru.yandex.practicum.filmorate.model.Genre;
убрал

2023-02-17 09:32 UTC, closed without merging